-- soal 1
-- DESC employees;
-- SELECT * FROM employees;
-- INSERT INTO employees
-- VALUES ('1009', 'Hidayat','Syarif','x1000','syaarifhd@gmail.com','1','1003','Vp Marketing');
--        ('1004', 'Fatwa','Faiz','x1005','faiz@gmail.com','2','1002','Vp Marketing'),
--        ('1005', 'Fikri','Muhammad','x1010','fikri@gmail.com','3','1002','Vp Marketing');
--  
 
 -- Soal 2
-- SELECT * FROM offices;
-- INSERT INTO offices
-- VALUES ('8', 'Gowa','+62 01 2345 6789','01 katangka','floor #1','sulsel','IDN','01234','SEAN');
-- 
-- UPDATE employees
-- SET officeCode = "8"
-- WHERE officeCode = "4" AND jobTitle = "Sales Rep";
-- 
-- SELECT * FROM employees;
-- 